import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";

const urbanist = localFont({
  src: "./fonts/Urbanist-VariableFont_wght.ttf",
  variable: "--font-urbanist",
  weight: "100 900",
});

const urbanistItalic = localFont({
  src: "./fonts/Urbanist-Italic-VariableFont_wght.ttf",
  variable: "--font-urbanist",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${urbanistItalic.variable} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
